services:

    backend:
        build: ./backend
        container_name: backend
        command: sh /app/entrypoint.sh
        restart: unless-stopped            
        volumes:
            - ./backend:/app
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env
        environment:
            DJANGO_SETTINGS_MODULE: core.settings
        networks:
            - app_network    
        
    frontend:
        build: ./frontend
        container_name: frontend
        command: npm run dev -- --host 0.0.0.0
        restart: unless-stopped
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        ports: 
            - "5173:5173"
        stdin_open: true
        tty: true
        networks:
            - app_network    
        
    db:
        image: postgres:16
        container_name: postgres_db
        restart: always
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d serpagostec_db"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - app_network    

volumes:
    postgres_data:           

networks:
  app_network:    
