# Generated by Django 6.0.5 on 2026-05-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_technician_tecnico_ordenservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='metodo_pago',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=20),
        ),
    ]
