# Generated by Django 6.0.5 on 2026-05-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_ordenservicio_metodo_pago_alter_ordenservicio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='metodo_pago',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta')], default='cash', max_length=20),
        ),
    ]
