# Generated by Django 6.0.5 on 2026-05-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_ordenservicio_metodo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenservicio',
            old_name='closed_at',
            new_name='fecha_cierre',
        ),
        migrations.RenameField(
            model_name='ordenservicio',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
    ]
