# Generated by Django 6.0.5 on 2026-05-26 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_closed_at_ordenservicio_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta')], max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='services.ordenservicio')),
            ],
        ),
    ]
