# Generated by Django 6.0.5 on 2026-05-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_piezas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='total_piezas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='numero_orden',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
