# Generated by Django 6.0.6 on 2026-06-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_ordenservicio_total_piezas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('total_ordenes', models.PositiveIntegerField(default=0)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_comision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_piezas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='pago_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='services.pagotecnico'),
        ),
    ]
