# Generated by Django 6.0.6 on 2026-06-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_pagotecnico_ordenservicio_pago_tecnico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagotecnico',
            options={'verbose_name': 'Historial de pago', 'verbose_name_plural': 'Historial de pagos'},
        ),
    ]
